jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg curl rar python3 python3-pip atomicparsley aria2 -y
          python3 -m pip install --upgrade yt-dlp

      - name: Run Video Download (yt-dlp)
        run: |
          yt-dlp --config-location dl.conf

      - name: Process and Compress Files
        run: |
          python3 ./deal_download_files.py

      - name: Release Packages
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false
          title: ${{ github.run_id }}
          files: |
            result/*
